### ISSUE TITLE
Missing dependency org/openqa/selenium/DeviceRotation after update to 5.0.4

### ISSUE THREAD

**Issue by mpau** [appium/java-client#748]
## Description

After adding the maven dependency for the appium java client to 5.0.4, I get a missing dependency org/openqa/selenium/DeviceRotation

## Environment

* java client build version or git revision if you use some shapshot: 5.0.4
* Desktop OS/version used to run Appium if necessary: macOS 10.12.6

## Details

I've added to my pom file the dependency:
<dependency>
    <groupId>io.appium</groupId>
    <artifactId>java-client</artifactId>
    <version>5.0.4</version>
</dependency>

If I start now a test (worked fine with 3.2.0) I will get the error:
Error:Groovyc: While compiling tests of mate-mobile: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class io.appium.java_client.AppiumDriver <T extends org.openqa.selenium.WebElement> due to missing dependency org/openqa/selenium/DeviceRotation

## Ecxeption stacktraces

https://gist.github.com/mpau/6f9c1710ab164372c6f22283ba3681c8

**Comment by mykola-mokhnach** [comment]
Can you show you project maven/gradle config?

**Comment by mpau** [comment]
Sorry to waste your time. The problem was a bug in my head ;-) There was another dependency in the pom file of an internal framework, that comes with an totaly outdated selenium version. But it was before the appium java-client dependency in the pom. So the java-client didn't had the chance to get the correct selenium version at all.
