### ISSUE TITLE
AppiumDriver installApp() doesn't work in version 1.4.0

### ISSUE THREAD

**Issue by MariaSoluto** [appium/java-client#57]
It didn't work in previous versions, but I was hoping it would be fixed by now. I just updated to 1.4.0 and there's still a problem with using the installApp() method. This is the error I get:

org.openqa.selenium.WebDriverException: ERROR running Appium command: string is not a function
Command duration or timeout: 7 milliseconds
Build info: version: '2.42.0', revision: '5e824302019c86eae9c8c3ca9155e7307b410cf8', time: '2014-05-24 09:48:41'
System info: host: 'PC', ip: '172.18.1.14', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0'
Driver info: io.appium.java_client.AppiumDriver
Capabilities [{app=MdnFetcher.apk, appPackage=com.example.MdnFetcher, warnings={}, appWaitActivity=.MyActivity, databaseEnabled=false, version=, platform=XP, appActivity=.MyActivity, desired={app=MdnFetcher.apk, appPackage=com.example.MdnFetcher, appActivity=.MyActivity, newCommandTimeout=300, autoLaunch=false, platformVersion=4.4.2, appWaitActivity=.MyActivity, browserName=, platformName=Android, version=, platform=Windows}, newCommandTimeout=300, autoLaunch=false, platformVersion=4.4.2, webStorageEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=Android}]
Session ID: c9148407-5281-44f8-bea6-289392dc6ce3
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:191)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:76)
    at io.appium.java_client.AppiumDriver.installApp(AppiumDriver.java:397)
