### ISSUE TITLE
PullFile method return InvocationTargetException while running with Java 9

### ISSUE THREAD

**Issue by Kpamnani1** [appium/java-client#896]
## Description

Trying to pull a file from the Android emulator using driver.PullFile (path). An InvocationTargetException is returned. Same code worked fine with Java 1.8

## Environment

* java client build version 6.0.0-BETA5
* Appium server version v1.7.2
* Desktop OS/version used to run Appium : Runnig on Windows 7 
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test Android 7 
* Real device or emulator/simulator: emulator

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]
public void pullC2v() throws IOException {
        log.info("Fetching C2V from Device");

        byte[] returnData = driver.pullFile("sdcard/request.c2v");
        Path requestC2vPath=Paths.get(System.getProperty("user.dir"), "src", "main", "resources", "scripts", "request.c2v");
        File fs = new File(requestC2vPath.toString());
        FileOutputStream fos = new FileOutputStream(fs);
        fos.write(returnData);
        fos.flush();
        fos.close();

## Ecxeption stacktraces

https://gist.github.com/Kpamnani1/6ff3e51fc0c752fe939566604beca00a

## Link to Appium logs

https://gist.github.com/Kpamnani1/ed608ac7663f423b801fd0d16c039524

**Comment by mykola-mokhnach** [comment]
This is most likely Java9 issue: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by Kpamnani1** [comment]
I have created a separate issue  for above mentioned item
https://github.com/appium/java-client/issues/900
