### ISSUE TITLE
Need to include gson library

### ISSUE THREAD

**Issue by amedvedjev** [appium/java-client#48]
by some reason driver fails to start with 1.2.0 version or above.
working correctly with 1.1.0

other libs in project:
- selenium-java-2.41.0
- selenium-server-standalone-2.41.0

pls suggest solution.

code:

```
        capabilities = DesiredCapabilities.android();
        capabilities.setCapability("automationName", "Appium");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "4.4.2");
        capabilities.setCapability("appPackage", "some_package_name");
        capabilities.setCapability("appActivity", ".some_app_activity");
        fileName =  ConfigProperties.getProperty("androidBuild");
        File appDir = new File(userDir, fileName);
        capabilities.setCapability("app", appDir.getAbsolutePath());
        process = Runtime.getRuntime().exec("appium -q");
        driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
```

Error:

java.lang.NoSuchMethodError: org.openqa.selenium.remote.ErrorHandler.<init>(Lorg/openqa/selenium/remote/ErrorCodes;Z)V

after updating libs to:
- selenium-java-2.42.2
- selenium-server-standalone-2.42.2

error changes to (e.g. with 1.3.0 java client):
ava.lang.NoClassDefFoundError: com/google/gson/JsonParser
    at io.appium.java_client.ComplexFind.<clinit>(ComplexFind.java:16)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:46)
    at com.cardola.tests.util.AppiumSetup.getDriver(AppiumSetup.java:117)
    at com.cardola.tests.util.AppiumSetup.prepareDriver(AppiumSetup.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
    at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:525)
    at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:202)
    at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:130)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:260)
    at org.testng.SuiteRunner.run(SuiteRunner.java:223)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
    at org.testng.TestNG.run(TestNG.java:900)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:110)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonParser
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 28 more
