### ISSUE TITLE
Getting this error when i upgraded my appium java client to 6.1.0- java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V

### ISSUE THREAD

**Issue by JayasriPV** [appium/java-client#1231]
## Description

I upgraded my appium java client from 4.1.2 to 6.1.0, added selenium-java -3.12.0 and guava-23.0 dependency in my POM file

## Environment

* java client build version or git revision if you use some shapshot:NA
* Appium server version or git revision if you use some shapshot:NA
* Desktop OS/version used to run Appium if necessary: MAC 10.14.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: NA
* Mobile platform/version under test: Android Nexus
* Real device or emulator/simulator: emulator

## Details

This error is removed when i add them as external JAR files in my project but i need them to add under POM file so to make them generalise

## Code To Reproduce Issue [ Good To Have ]

Currently used dependency:

<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>6.1.0</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.12.0</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.12.0</version>
		</dependency>

<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>23.0</version>
		</dependency>

## Link to Appium logs

java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:245)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:578)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:93)
	at com.xome.mobile.testframework.appiumdrivercapabilities.AppiumDriverCapabilities.appLauncher(AppiumDriverCapabilities.java:105)
	at com.xome.mobile.testframework.appiumdrivercapabilities.AppiumDriverCapabilities.testSetupHelper(AppiumDriverCapabilities.java:448)
	at com.xome.mobile.testframework.newtests.BasicTests.initialize(BasicTests.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)

**Comment by saikrishna321** [comment]
remove the selenium dependencies, java-client comes with selenium.

**Comment by JayasriPV** [comment]
When i remove selenium dependencies then i get the below error:

java.lang.NoClassDefFoundError: org/openqa/selenium/remote/ProtocolHandshake

**Comment by saikrishna321** [comment]
@JayasriPV Can you please clear cache and restart your IDE and try.

**Comment by JayasriPV** [comment]
I cleared cache and restarted, tried with the latest java client 7.2.0, i get the below error

java.lang.NoSuchMethodError: org.openqa.selenium.remote.http.HttpClient$Factory.createDefault()Lorg/openqa/selenium/remote/http/HttpClient$Factory;

Also i have the dependencies of Selenium-java and selenium-server  to 3.141.59 and guava to 28.0-jre

**Comment by JayasriPV** [comment]
When i add the same dependencies as in the previous then i am getting the same error:
java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V

**Comment by JayasriPV** [comment]
Any solution to solve any of the issues.

**Comment by saikrishna321** [comment]
https://github.com/appium/java-client/issues/1231#issuecomment-531140728

You need to remove the selenium dependencies from your Pom.xml and guava

**Comment by JayasriPV** [comment]
When i remove selenium and guava dependencies and have the java-client as 7.0.0 then i get the below error:

java.lang.NoClassDefFoundError: org/openqa/selenium/remote/ProtocolHandshake

**Comment by jayandran-Sampath** [comment]
Hi @JayasriPV Can you please provide the code snippet & appium logs?

**Comment by JayasriPV** [comment]
https://gist.github.com/JayasriPV/5fccd2dc1c56c27990dd9312dd407306.js - java code for driver initiation, called by another method. Error is thrown during the driver creation

Cant provide appium logs as session itself is not created.

java.lang.NoClassDefFoundError: org/openqa/selenium/remote/ProtocolHandshake
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:95)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
	at com.xome.mobile.testframework.appiumdrivercapabilities.AppiumDriverCapabilities.appLauncher(AppiumDriverCapabilities.java:108)
	at com.xome.mobile.testframework.appiumdrivercapabilities.AppiumDriverCapabilities.testSetupHelper(AppiumDriverCapabilities.java:451)
	at com.xome.mobile.testframework.newtests.BasicTests.initialize(BasicTests.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)

**Comment by JayasriPV** [comment]
When i add selenium-java dependency in my pom file- 3.12.0 and currently my java-client is 7.2.0, then i get the below error:

java.lang.NoSuchMethodError: org.openqa.selenium.remote.http.HttpClient$Factory.createDefault()Lorg/openqa/selenium/remote/http/HttpClient$Factory;
	at io.appium.java_client.remote.AppiumCommandExecutor.<init>(AppiumCommandExecutor.java:93)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:95)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
	at com.xome.mobile.testframework.appiumdrivercapabilities.AppiumDriverCapabilities.appLauncher(AppiumDriverCapabilities.java:101)
	at com.xome.mobile.testframework.appiumdrivercapabilities.AppiumDriverCapabilities.testSetupHelper(AppiumDriverCapabilities.java:444)
	at com.xome.mobile.testframework.newtests.BasicTests.initialize(BasicTests.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)

**Comment by JayasriPV** [comment]
Please follow the below gist:
https://gist.github.com/JayasriPV/294e132706d41532a9d6755694474469.js

**Comment by Zamo2019** [comment]
I am also having the same issues all of a sudden last week all of my tests were running smooth.

Error Message: 
java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V

Appium Logs: N/A.   As I am unable to start a session

**Comment by JayasriPV** [comment]
Hi I resolved this issue by adding guava dependency in pom file

**Comment by Zamo2019** [comment]
Thanks for the feedback, however I also resolved the issue by upgrading the Selenium dependency to the latest version released in 2020.

I checked Selenium release notes.

**Comment by benzionyunger** [comment]
Thanks for the update!
Upgrading my Selenium and Appium dependencies also resolved the same NoSuchMethodError for me too.

**Comment by vikramjelije** [comment]
Getting this error when using the latest latest version (7.3.0) version of io.appium:java-client

**Comment by vikramjelije** [comment]
Please suggest the solution for this error

**Comment by benzionyunger** [comment]
What version is your Selenium client? 
This is my Maven  dependency:
 ```
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
```

**Comment by vikramjelije** [comment]
> What version is your Selenium client?
> This is my Maven dependency:
> 
> ```
> <dependency>
>            <groupId>org.seleniumhq.selenium</groupId>
>            <artifactId>selenium-java</artifactId>
>            <version>3.141.59</version>
>        </dependency>
> 
I didn't add any specific dependency for selenium as am using the io.appium with version 7.3.0, it internally uses the same 3.141.59 version of selenium.
