### ISSUE TITLE
Java client 5.0.0-BETA8, throws java.lang.NoClassDefFoundError: org/openqa/selenium/, with selenium java 2.47.0

### ISSUE THREAD

**Issue by VenkateshPS** [appium/java-client#648]
## Description

Java client 5.0.0-BETA8, throws below error with dependency, works fine with selenium-java 3.4.0
<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.47.0</version>
		</dependency>

  **java.lang.NoClassDefFoundError: org/openqa/selenium/
NoSuchSessionException
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:111)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)**

## Environment

Java client 5.0.0-BETA8,
1..6.5 beta
 Real device 

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by mykola-mokhnach** [comment]
I don'r think this is a bug - newer Appium driver versions are not obliged to support old selenium stuff. You can try to downgrade java client if the old lib is really needed.

**Comment by VenkateshPS** [comment]
Agree, but would be good if it throws some meaningful exception, like upgrade your Selenium server version.

**Comment by SrinivasanTarget** [comment]
Between why do we need to use Selenium dependency(older version) along with java client dependency when it comes with its latest selenium dependency already. Java-client is not backward compatible with selenium. Though meaningful error makes sense.
